language: scala

scala:
  - 2.11.8

jdk:
  - oraclejdk8

before_script:
  # default $SBT_OPTS is irrelevant to sbt launcher
  - unset SBT_OPTS
  - chmod +x ./bin/travisci
  - ./bin/travisci

script:
  - travis_retry ./sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
  - ./sbt ++$TRAVIS_SCALA_VERSION coverageAggregate

after_success:
  - bash <(curl -s https://codecov.io/bash)
